name: tic_tac_toe

packages:
  - backend
  - frontend

scripts:
  backend:
    run: cd backend && dart_frog dev --port=8080
    description: Start the Dart Frog backend
  frontend:
    run: cd frontend && flutter run --target lib/main.dart
    description: Start the Flutter frontend
